[package]
name = "RustPlanets"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.8.5"
macroquad = "0.4.13"
csv = "1.3.1"
serde = { version = "1.0.217", features = ["derive"] }
phf = { version = "0.11.3" , features = ["macros"]}